### ISSUE TITLE
use non-durable subscription?

### ISSUE THREAD

**Issue by foragerr** [Appdynamics/websphere-message-broker-extension#1]
Would the extension still work if the subscription is changed to non-durable?

[link](https://github.com/Appdynamics/ibm-websphere-msg-broker-monitor/blob/dd14f06152eebf2aae1911a9f2ed9504178bcf1a/src/main/java/com/appdynamics/extensions/wmb/WmbMonitor.java#L77)

**Comment by kunalgupApDx** [comment]
Hi,

There is a critical bug in the extension and we investigating on fixing it.
Until then, please refrain using this extension.

Thanks,
Kunal

On Wed, Jun 15, 2016 at 11:22 AM, RaGe <notifications@github.com> wrote:

> Would the extension still work if the subscription is changed to
> non-durable?
>
> link
> <https://github.com/Appdynamics/ibm-websphere-msg-broker-monitor/blob/dd14f06152eebf2aae1911a9f2ed9504178bcf1a/src/main/java/com/appdynamics/extensions/wmb/WmbMonitor.java#L77>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Appdynamics/ibm-websphere-msg-broker-monitor/issues/1>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGz89ebm4_jzytLx1yHy2vYn75_Pm9s4ks5qMELugaJpZM4I2pjK>
> .
>



-- 
* Kunal Gupta * | Principle Software Engineer
*AppDynamics*
Monitor your Apps in Production. Now.
Watch <http://www.appdynamics.com/player/whydemo.php> our Video | Download
<http://www.appdynamics.com/products-free-download.php> AppDynamics for
Free
Twitter <http://www.twitter.com/appdynamics> | Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf> |
appdynamics.com <http://www.appdynamics.com>

**Comment by foragerr** [comment]
Thanks for the heads up Kunal. Would you be able to share any information around what the bug is about?

**Comment by kunalgupApDx** [comment]
There is a connection leak

On Wed, Jun 15, 2016 at 3:36 PM, RaGe <notifications@github.com> wrote:

> Thanks for the heads up Kunal. Would you be able to share any information
> around what the bug is about?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Appdynamics/ibm-websphere-msg-broker-monitor/issues/1#issuecomment-226340394>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGz89TRVnl6XLPxmNaF46CwSBFqCt3QQks5qMH5SgaJpZM4I2pjK>
> .
>



-- 
* Kunal Gupta * | Principle Software Engineer
*AppDynamics*
Monitor your Apps in Production. Now.
Watch <http://www.appdynamics.com/player/whydemo.php> our Video | Download
<http://www.appdynamics.com/products-free-download.php> AppDynamics for
Free
Twitter <http://www.twitter.com/appdynamics> | Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf> |
appdynamics.com <http://www.appdynamics.com>

**Comment by foragerr** [comment]
Ah, Thanks. Would really appreciate it if you can update this issue once you have a resolution.

**Comment by kunalgupApDx** [comment]
I have fixed this issue
